new git commands

diff --git a/bin/gd b/bin/gd
--- a/bin/gd
+++ b/bin/gd
@@ -2,13 +2,22 @@
 
 set -e
 
-# Ensure two arguments are provided
-if [ "$#" -ne 2 ]; then
-    echo "Usage: $0 <search_term> <branch_name>"
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $0 <search_term>"
     exit 1
 fi
 
 SEARCH_TERM="$1"
-BRANCH_NAME="$2"
 
-git diff "$BRANCH_NAME"... -G"$SEARCH_TERM" --name-only | nvim-qf
+if ! command -v gum > /dev/null 2>&1; then
+    echo "Error: gum is not installed. Exiting."
+    exit 1
+fi
+
+COMMIT=$(git log --oneline | gum choose | awk '{print $1}')
+
+if [ -z "$COMMIT" ]; then
+    exit 1
+fi
+
+git diff "$COMMIT" -G"$SEARCH_TERM" --name-only | nvim-qf
